-- MySQL Database Schema and Seed Data for LivCrowd

-- IMPORTANT: This schema is auto-generated by Spring Boot Data JPA (ddl-auto=update).
-- The script below seeds initial configuration data and initial admin superuser.
-- Note: 'password' field holds a BCrypt hash of 'Admin@123'

INSERT IGNORE INTO users (username, email, password_hash, role, created_at) VALUES 
('admin', 'admin@livcrowd.com', '$2a$10$UoE3hVvN2Yv/I4z.6/YnC.WdK3L6kZ.r8i5/9O.ZJ/7T1Lh6/N4P2', 'ADMIN', NOW()),
('user1', 'user1@livcrowd.com', '$2a$10$UoE3hVvN2Yv/I4z.6/YnC.WdK3L6kZ.r8i5/9O.ZJ/7T1Lh6/N4P2', 'USER', NOW());

INSERT IGNORE INTO places (id, name, category, address, capacity, is_active, created_at) VALUES
(1, 'City General Hospital', 'HOSPITAL', '120 Health Ave', 500, true, NOW()),
(2, 'Neon Cyber Cafe', 'CAFE', '4th Street, Downtown', 80, true, NOW()),
(3, 'Tech Institute', 'COLLEGE', 'University Road', 2000, true, NOW()),
(4, 'Global Innovators Hub', 'OFFICE', 'Tech Park, Building C', 1500, true, NOW()),
(5, 'Future Sounds Festival', 'EVENT', 'Grand Arena', 5000, true, NOW()),
(6, 'Midnight Coffee', 'CAFE', 'Dark Mode Street 42', 50, true, NOW());

INSERT IGNORE INTO place_configs (place_id, low_threshold, medium_threshold, snapshot_interval_sec, always_crowded) VALUES
(1, 40, 80, 30, true),
(2, 30, 70, 30, false),
(3, 40, 80, 30, false),
(4, 30, 70, 30, false),
(5, 50, 85, 30, true),
(6, 30, 70, 30, false);
